### ISSUE TITLE
Spoof validation: See documentation to allow this combination

### ISSUE THREAD

**Issue by mischa78** [thoughtbot/paperclip#1462]
When uploading a PHP file I get:

> [paperclip] Content Type Spoof: Filename code.php (["application/x-httpd-php"]), content type discovered from file command: text/x-php. See documentation to allow this combination.

in my log. How do I allow this combination? I don't seem to be able to find it in the documentation.

I have developed an asset manager to which you can upload any kind of file. By accident I discovered that PHP files are not accepted due to this content type mismatch, but I cannot predict for which other file types a mismatch will happen. It seems this makes Paperclip in its current form unusable for my project.

I think Paperclip is great and I want to keep using the latest version. What can I do??

**Comment by maclover7** [comment]
Hi everybody! Is this still an issue for you in Paperclip; I know this issue is from approximately 1 year ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by jspizziri** [comment]
Yes, this is still an issue however, there are several issues which address this same problem.

**Comment by maclover7** [comment]
Is this fixed with #1839 ?

**Comment by tute** [comment]
pinging this thread again: is this fixed with #1839?

**Comment by mischa78** [comment]
Does the latest release contain this fix? Or do I have to test with master?

**Comment by mischa78** [comment]
I've tested again master and the issue doesn't seem to be fixed. I still get this for .php files:

> [paperclip] Content Type Spoof: Filename file.php (["application/x-httpd-php"]),
> content type discovered from file command: text/x-php. See documentation to allow this combination.

and this for .sql files:

> [paperclip] Content Type Spoof: Filename file.sql (["application/x-sql"]),
> content type discovered from file command: text/plain. See documentation to allow this combination.

**Comment by Joshfindit** [comment]
I'm developing a non-public app.
Can I specify that a class can accept * content types, thus disabling the need to allow specific types?

**Comment by tute** [comment]
Does the snippet detailed in the README file fix your issue? See: Or the snippet in the README file? https://github.com/thoughtbot/paperclip#security-validations

**Comment by tute** [comment]
> Thanks, this solves the problem for PHP files, but I still cannot predict for what other file types a mismatch will happen. It may even be so that a mismatch happens on one system and not on another. This makes Paperclip unusable in open source projects that can be installed on any system.

The problem is not where paperclip is installed, but where are files coming from. Windows vs Mac or Linux, Windows with or without Office installed, different browsers, will report different content types for the very same files. We won't disable content type validators and continue to push this complexity onto our users to make it secure by default. As we all know, security comes at odds with convenience.

If you want and know how to do it, and it's safe for your case, you could disable all validations. But it's not easy and that's the point: only people who really know what they are doing should disable them.

Because this issue links to other related issues that contain all the context discussed here, I'll close this in favor of the other ones, where we have more in depth explanations of potential solutions and their related problems.

Thank you for your time reporting and discussing this! 🎉

**Comment by mischa78** [comment]
> The problem is not where paperclip is installed, but where are files coming from. Windows vs Mac or Linux, Windows with or without Office installed, different browsers, will report different content types for the very same files.

This is at odds with what @ghost says above. If this is true, then this problem doesn't concern just open source projects installed on different servers, but it would concern every user of Paperclip. You'd have to manually set lots of `Paperclip.options[:content_type_mappings]` to deal with possible mismatches caused by browsers, operating systems and Office installs that apparently cannot be predicted up front.

I understand and share your security concerns, that's why I'd rather not disable, but unfortunately I have no choice if there is no way of knowing if spoof validation will fail on unspoofed files. I will read up on the discussion/potential solutions and related problems in the other issues. Thanks for your feedback.

**Comment by tute** [comment]
> This is at odds with what @ghost says above. If this is true, then this problem doesn't concern just open source projects installed on different servers, but it would concern every user of Paperclip. You'd have to manually set lots of `Paperclip.options[:content_type_mappings]` to deal with possible mismatches caused by browsers, operating systems and Office installs that apparently cannot be predicted up front.

Unfortunately that is the case as of today: https://github.com/thoughtbot/paperclip/labels/Spoof%20related%20or%20Mime%20types. Hopefully we can make it better for everyone.

**Comment by mischa78** [comment]
Sorry if I sounded a bit harsh. I still like Paperclip a lot and I appreciate the work you and other contributors are doing.

**Comment by tute** [comment]
All good. Thanks!

**Comment by svobom57** [comment]
I have troubles with uploading .hex files for Arduino, similar error comes up:

`Command :: file -b --mime '/tmp/b904cd4cd1d9895f8420a0991eefeccc20160908-16126-1vj2n2x.hex'
[paperclip] Content Type Spoof: Filename initial_sketch.hex (text/x-hex from Headers, [] from Extension), content type discovered from file command: text/plain. See documentation to allow this combination.
`

But when i add `Paperclip.options[:content_type_mappings] = { hex: 'text/plain' }` into an initializer. It still fails. It just says _is invalid_.

Logs don't show much:

`     Parameters: {"utf8"=>"✓", "authenticity_token"=>"ebrDEFJeqsdS4AsUpDqHddMxQETe1qr+IH+dbAyRnhlbwXc1IdUekLYLD0riM2T7uljUejk+c9rMq6XkTFop+Q==", "entities_app"=>{"name"=>"", "description"=>"", "version"=>"", "icon"=>"", "sketch"=>#<ActionDispatch::Http::UploadedFile:0x00000007e15af8 @tempfile=#<Tempfile:/tmp/RackMultipart20160908-16230-1l3yfbi.hex>, @original_filename="initial_sketch.hex", @content_type="text/x-hex", @headers="Content-Disposition: form-data; name=\"entities_app[sketch]\"; filename=\"initial_sketch.hex\"\r\nContent-Type: text/x-hex\r\n">}, "commit"=>"Try creating once again"}
  Entities::User Load (0.8ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 1]]
Command :: file -b --mime '/tmp/b904cd4cd1d9895f8420a0991eefeccc20160908-16230-thzdl1.hex'
   (0.3ms)  BEGIN
Command :: file -b --mime '/tmp/b904cd4cd1d9895f8420a0991eefeccc20160908-16230-1wjhx9v.hex'
   (0.3ms)  ROLLBACK

`

Am I doing something wrong?

**Comment by svobom57** [comment]
Ok so update

Following setup fixed this. I don't know what's happening, or why is it working:

_config/initializers/paperclip.rb_
`
Paperclip.options[:content_type_mappings] = { hex: %w(text/x-hex text/plain) }`

_model_
```ruby
has_attached_file :sketch
    validates_attachment :sketch, presence: true,
                         content_type: { content_type: %w(text/x-hex text/plain) },
                         size: { less_than: 5.megabytes }
```
