### ISSUE TITLE
Validation on URI.parse(cloud_front_url)

### ISSUE THREAD

**Issue by alvarezloaiciga** [thoughtbot/paperclip#1470]
When I am trying to store an image located in a cloud-front url I am getting:

```
Validation failed: Image has an extension that does not match its contents
```

I am doing this:

``` ruby
image = URI.parse(cloud_front_url)
User.create(image: image)
```

Cloudfront images don't have an extension on their url. Is there a way to make this work ? I tried putting the `do_not_validate_attachment_file_type :image` but it is still doing the validation.

**Comment by mikemccallen** [comment]
For The new Ruby 2.1 and Rails 4.2 
Add in your models 
validates_attachment_content_type :asset, :content_type => ["image/jpeg", "image/gif", "image/png"]
Or 
validates_attachment_content_type :asset, :content_type => /\Aimage\/.*\Z/

To validate all types

**Comment by mjodko** [comment]
A workaround that might make a bit more sense (since it doesn't eliminate content type spoof checking where it is desired):

```ruby
# config/initializers/paperclip.rb
require 'paperclip/media_type_spoof_detector'

module Paperclip
  class MediaTypeSpoofDetector
    old_spoofed = instance_method(:spoofed?)

    define_method(:spoofed?) do
      if supplied_file_content_types.count > 0
        old_spoofed.bind(self).()
      else
        false
      end
    end
  end
end
```

**Comment by maclover7** [comment]
Hi everybody! Is this still an issue for you in Paperclip; I know this issue is from approximately 1 year ago. If it is still an issue, can you please provide the code that's causing you the error? Thanks!

**Comment by alvarezloaiciga** [comment]
@maclover7 not an issue anymore for me

**Comment by maclover7** [comment]
@jferris @jyurek Please close issue, problem appears to be solved.

**Comment by manfe** [comment]
The method below

```ruby
do_not_validate_attachment_file_type
```

Was ignored by the paperclip because the command

```console
/usr/bin/convert
```
Was not installed. After that I installed the Imagemagick via apt-get

```console
sudo apt-get install imagemagick
```

The command started to work, and paperclip works fine.
You can verify if convert is installed using:

```console
which convert
```

If the return is `/usr/bin/convert`

Create or edit the paperclip initializer adding: `config/initializer/paperclip.rb`
```ruby
Paperclip.options[:command_path] = '/usr/bin'
```

Now it's ok here with Rails 4.2, Ruby 2.1.5, Paperclip 4.2.1

**Comment by vike27** [comment]
Running into this issue myself with rails 4.2, ruby 2.1.5, Paperclip 4.2 on windows

**Comment by te-chris** [comment]
Running into this on ruby 2.2.1, rails 4.2,  It's blowing up with a WMA file which is being parsed by file as video/x-ms-asf

**Comment by jspizziri** [comment]
+1

Same problem with ruby 2.1.0 and rails 4.2.1. 

xxx.mp3 Mime type = `audio/mpeg`

**Comment by jetaggart** [comment]
I have a slightly different use case but this is an issue for me. I have a form where I want to allow any kind of file to be uploaded (ruby, binary), etc. as I'm only storing them for later retrieval. However, I don't want to just hack papertrail to remove the spoofing checks, as I'm using it elsewhere where I really do care about those things. Is there any way to turn off the spoof checking for a single model?

**Comment by maclover7** [comment]
Is this fixed with #1839 ?

**Comment by jetaggart** [comment]
No I still receive `Validation failed: Attachment has an extension that does not match its contents` for `.xlsx` files (Excel specifically). Even if that were to work, what would I need to do to support `.rb` file uploads?

**Comment by lancedikson** [comment]
I have the same `spoofed_media_type` error with uploaded `application/ogg`/`audio/ogg` file.

**Comment by brodjustice** [comment]
Have the same problem with Peperclip 5.1.0 and .ogv:

`[paperclip] Content Type Spoof: Filename xxx.ogv (video/ogg from Headers, ["video/ogg"] from Extension), content type discovered from file command: application/ogg. See documentation to allow this combination.`

**Comment by mb21** [comment]
@maclover7 I'm running into this with facebook API image URLs like `https://external.xx.fbcdn.net/safe_image.php?d=dfdf234asdf56f78`, obviously the validator complains that .php doesn't match the JPEG content type.

Would be great if I could disable that check in only that place in my app, e.g. something like `Image.new file: url, suffix_validation: false`

**Comment by vedant1811** [comment]
I am having the same problem with .ogv files.

**Comment by ashvin-chauhan** [comment]
@manfe Thanks your solution worked for me :slightly_smiling_face:

**Comment by kaikuchn** [comment]
I had a similar root-cause as @manfe. In my case the `file` command was missing which resulted in paperclip getting nil as content type and rejecting everything. (God damn minimal docker images 😆 )

**Comment by bryanwoods** [comment]
I'm having this issue using Rails version 5.2.0.beta2 with models that have multiple attachments of content type `application/pdf`

**Comment by mike-burns** [comment]
Looks like we found a workaround, closing.
