### ISSUE TITLE
validates attachment size: ArgumentError - comparison of String with ... failed

### ISSUE THREAD

**Issue by capnregex** [thoughtbot/paperclip#1692]
I came across this issue today when I tried to have a secondary form update some other field on my record without touching my attachment in any way.. 

In the model.. 
```ruby
class Product < ActiveRecord::Base
 ...
  has_attached_file :image, :styles => { 
    :medium => "300x300", 
    :thumb => "100x100"
  }
  validates_attachment :image, content_type: { content_type: /^image\/(gif|png|jpe?g)$/}, size: { in: 0..10.megabytes }
```

The Controller (singular resource)
```ruby
class PrintsController < ApplicationController
  load_and_authorize_resource :product, find_by: :key

  def show
  end

  def edit
  end

  def update
    if @product.update(print_params)
      redirect_to product_print_path(@product)
    else
      render action: 'edit'
    end
  end

protected
  def print_params
    params.require(:product).permit(:print_url)
  end

end
```

```backtrace
ArgumentError - comparison of String with 10485760 failed:
  paperclip (4.2.0) lib/paperclip/validators/attachment_size_validator.rb:27:in `block in validate_each'
  paperclip (4.2.0) lib/paperclip/validators/attachment_size_validator.rb:23:in `validate_each'
  activemodel (4.0.2) lib/active_model/validator.rb:153:in `block in validate'
  activemodel (4.0.2) lib/active_model/validator.rb:150:in `validate'
  activesupport (4.0.2) lib/active_support/callbacks.rb:283:in `_callback_before_1564'
  activesupport (4.0.2) lib/active_support/callbacks.rb:597:in `_run__3469093354852466030__validate__callbacks'
  activesupport (4.0.2) lib/active_support/callbacks.rb:80:in `run_callbacks'
  activemodel (4.0.2) lib/active_model/validations.rb:373:in `run_validations!'
  activemodel (4.0.2) lib/active_model/validations/callbacks.rb:106:in `block in run_validations!'
  activesupport (4.0.2) lib/active_support/callbacks.rb:373:in `_run__3469093354852466030__validation__callbacks'
  activesupport (4.0.2) lib/active_support/callbacks.rb:80:in `run_callbacks'
  activemodel (4.0.2) lib/active_model/validations/callbacks.rb:106:in `run_validations!'
  activemodel (4.0.2) lib/active_model/validations.rb:314:in `valid?'
  activerecord (4.0.2) lib/active_record/validations.rb:70:in `valid?'
  activerecord (4.0.2) lib/active_record/validations.rb:77:in `perform_validations'
  activerecord (4.0.2) lib/active_record/validations.rb:51:in `save'
  activerecord (4.0.2) lib/active_record/attribute_methods/dirty.rb:32:in `save'
  activerecord (4.0.2) lib/active_record/transactions.rb:270:in `block (2 levels) in save'
  activerecord (4.0.2) lib/active_record/transactions.rb:326:in `block in with_transaction_returning_status'
  activerecord (4.0.2) lib/active_record/connection_adapters/abstract/database_statements.rb:202:in `block in transaction'
  activerecord (4.0.2) lib/active_record/connection_adapters/abstract/database_statements.rb:210:in `within_new_transaction'
  activerecord (4.0.2) lib/active_record/connection_adapters/abstract/database_statements.rb:202:in `transaction'
  activerecord (4.0.2) lib/active_record/transactions.rb:209:in `transaction'
  activerecord (4.0.2) lib/active_record/transactions.rb:323:in `with_transaction_returning_status'
  activerecord (4.0.2) lib/active_record/transactions.rb:270:in `block in save'
  activerecord (4.0.2) lib/active_record/transactions.rb:281:in `rollback_active_record_state!'
  activerecord (4.0.2) lib/active_record/transactions.rb:269:in `save'
  app/controllers/prints_controller.rb:12:in `update'
```

**Comment by cdemyanovich** [comment]
I, too, found in one of my projects that one of the `*_file_size` database columns was a string instead of an integer. It might make sense to close this issue.

**Comment by tute** [comment]
@capnregex is this still an issue with paperclip?

**Comment by tute** [comment]
Related with https://github.com/thoughtbot/paperclip/issues/1798. I don't know why many users had that column as string. If it happens in paperclip, this should be fixed. Otherwise, it's not an issue with this project. Thank you all for your input!

**Comment by jufemaiz** [comment]
I can confirm that I'm still seeing this right now.

db/schema.rb

`
    t.string   "avatar_file_name",               limit: 255
    t.string   "avatar_content_type",            limit: 255
    t.integer  "avatar_file_size"
    t.datetime "avatar_updated_at"
`

psql:

`
 avatar_file_name               | character varying(255)      |
 avatar_content_type            | character varying(255)      |
 avatar_file_size               | integer                     |
 avatar_updated_at              | timestamp without time zone |
`

Error thrown when using validation of file size using "validates_attachment_size :avatar, less_than: 1.megabytes"

Stack thrown:

`
ArgumentError - comparison of String with 0 failed:
  activesupport (4.2.8) lib/active_support/number_helper/number_to_rounded_converter.rb:20:in `convert'
  activesupport (4.2.8) lib/active_support/number_helper/number_converter.rb:132:in `execute'
  activesupport (4.2.8) lib/active_support/number_helper/number_converter.rb:118:in `convert'
  activesupport (4.2.8) lib/active_support/number_helper/number_to_human_size_converter.rb:21:in `convert'
  activesupport (4.2.8) lib/active_support/number_helper/number_converter.rb:132:in `execute'
  activesupport (4.2.8) lib/active_support/number_helper/number_converter.rb:118:in `convert'
  activesupport (4.2.8) lib/active_support/number_helper.rb:238:in `number_to_human_size'
  paperclip (5.1.0) lib/paperclip/validators/attachment_size_validator.rb:74:in `human_size'
  paperclip (5.1.0) lib/paperclip/validators/attachment_size_validator.rb:88:in `max_value_in_human_size'
  paperclip (5.1.0) lib/paperclip/validators/attachment_size_validator.rb:32:in `block (2 levels) in validate_each'
  paperclip (5.1.0) lib/paperclip/validators/attachment_size_validator.rb:29:in `block in validate_each'
  paperclip (5.1.0) lib/paperclip/validators/attachment_size_validator.rb:23:in `validate_each'
  activemodel (4.2.8) lib/active_model/validator.rb:151:in `block in validate'
  activemodel (4.2.8) lib/active_model/validator.rb:148:in `validate'
  paperclip (5.1.0) lib/paperclip/validators.rb:68:in `block in create_validating_before_filter'
`
